### ISSUE TITLE
在 v3.0.0 无法使用插件，需要适配

### ISSUE THREAD

**Issue by TCOTC** [TechDecryptor/pot-app-tts-plugin-youdao#2]
https://github.com/pot-app/pot-desktop/issues/848#issuecomment-2185040654

模板仓库：https://github.com/pot-app/pot-app-tts-plugin-template

**Comment by TechDecryptor** [comment]
https://github.com/TechDecryptor/pot-app-tts-plugin-youdao/releases/tag/2.0.0

**Comment by TCOTC** [comment]
这个不知道为啥添加不了（虽然显示安装了）

![image](https://github.com/TechDecryptor/pot-app-tts-plugin-youdao/assets/78434827/dcc41979-b87f-4031-9a52-3533d3753804)

**Comment by TechDecryptor** [comment]
这是语音合成插件啊

**Comment by TCOTC** [comment]
噢，我还以为这个插件窗口是通用的（毕竟安装成功了），原来要切换到 `语音合成`
