### ISSUE TITLE
[Bug]在Pot 3.0无法朗读任何语言

### ISSUE THREAD

**Issue by mpbizn** [TechDecryptor/pot-app-tts-plugin-youdao#3]
如题，已将插件及Pot至最新
<img width="263" alt="PixPin_2024-06-24_10-03-58" src="https://github.com/TechDecryptor/pot-app-tts-plugin-youdao/assets/55294216/6eab3e97-e7f9-4ab5-8ae6-d1ca5886d81d">
<img width="600" alt="PixPin_2024-06-24_10-00-27" src="https://github.com/TechDecryptor/pot-app-tts-plugin-youdao/assets/55294216/483f3c2a-2b15-47b5-8a58-83e5ab27bc04">

**Comment by TechDecryptor** [comment]
是pot的问题，我看作者已经修了，去这儿下载https://github.com/pot-app/pot-desktop/actions/runs/9634834039
